version: '3'

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    env_file:
      - ./.env
  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
#      - ./config:/var/www/html/config:rw
#      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
      - ./config.ini.php:/var/www/html/config/config.ini.php
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - PLATFORM_ROUTES_MATOMO=http://matomo.localhost/
    ports:
      - 8080:80

volumes:
  db:
  matomo:
